import * as Invocation from 'iso-ucan/invocation'
import { Delegation } from 'iso-ucan/delegation'
import { EdDSASigner } from 'iso-signatures/signers/eddsa.js'
import { env } from 'node:process'

// export const AUTHOR_DID = 'did:key:z6Mkm2amevqzfDPo3V9fvV6efLxK4H2DvzuSkrcWFkVisMjJ'

export const getBearerToken = (authHeader?: string) => {
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    throw new Error('Invalid authorization header')
  }
  return authHeader.substring(7)
}

export const verifyDelegation = async (token: string) => {
  const delegation = await Delegation.fromString(token)

  if (!delegation.iss || delegation.iss !== env.AUTHOR_DID) {
    throw new Error('Token not generated by authorized party')
  }

  if (delegation.exp && delegation.exp < Date.now() / 1000) {
    throw new Error('Token has expired')
  }

  return delegation
}