import { Hono } from 'hono'
import { Delegation } from 'iso-ucan/delegation'
import { FC } from 'hono/jsx' // Import Hono's native JSX engine

type Bindings = {
  NOVEL_TEXT_KV: KVNamespace
  DB: D1Database
}

const app = new Hono<{ Bindings: Bindings }>()
const AUTHORIZED_ROOT_DID = "did:key:z6Mkm2amevqzfDPo3V9fvV6efLxK4H2DvzuSkrcWFkVisMjJ"

app.get('api/chapter/:slug', async (c) => {
  const slug = c.req.param('slug')
  const authHeader = c.req.header('Authorization')
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return c.text('Unauthorized', 401)
  }
  const token = authHeader.substring(7) // Remove "Bearer " prefix
  try {
    const delegation = await Delegation.fromString(token)
    console.log('Issuer:', delegation.iss, " Root DID:", AUTHORIZED_ROOT_DID)

    if (!delegation.iss || delegation.iss !== AUTHORIZED_ROOT_DID) {
      return c.text('Unauthorized: Token not generated by authorized party', 401)
    }
    console.log('Token expiration:', delegation.exp, 'Current time:', Date.now() / 1000)
    if (delegation.exp && delegation.exp < Date.now() / 1000) {
      console.log('CRITICAL Cloudflare thinks this token is expired. Expiration time:', delegation.exp, 'Current time:', Date.now() / 1000)
      return c.text('Unauthorized: Token has expired', 401)
    }
  } catch (error) {
    console.error('Error verifying token:', error)
    return c.text('Unauthorized: Invalid cryptographic signature', 401)
  }
  const chapterText = await c.env.NOVEL_TEXT_KV.get(slug)
  if (!chapterText) {
    return c.text('Chapter not found', 404)
  }
  return c.text(chapterText)
})

app.post('api/feedback', async (c) => {
  const feedback = await c.req.json()
  const { chapterSlug, feedbackText } = feedback

  // Store the feedback in the D1 database
  const query = `
    INSERT INTO feedback (chapter_slug, feedback_text)
    VALUES (?, ?)
  `
  await c.env.DB.prepare(query).bind(chapterSlug, feedbackText).run()

  return c.json({ message: 'Feedback submitted successfully' })
})

const HeadStyles: FC = () => {
  // FIXED: Explicit object mapping wrapper matching Hono documentation syntax rules
  const cssStyles = {
    __html: `
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        color: #1f2937;
        background: #ffffff;
        overflow: hidden;
        height: 100vh;
      }
      .toolbar {
        height: 56px;
        border-bottom: 1px solid #e5e7eb;
        display: flex;
        align-items: center;
        padding: 0 16px;
        gap: 16px;
        background: #fafafa;
      }
      .toolbar button {
        padding: 8px 12px;
        background: #ffffff;
        border: 1px solid #d1d5db;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 500;
      }
      .toolbar button:hover { background: #f3f4f6; }
      .novel-title { font-weight: 600; font-size: 1.1rem; margin-left: auto; margin-right: auto; }
      .workspace-container { display: flex; height: calc(100vh - 56px); position: relative; }
      .left-sidebar {
        width: 260px;
        border-right: 1px solid #e5e7eb;
        background: #f9fafb;
        overflow-y: auto;
        transition: transform 0.3s ease, margin-left 0.3s ease;
        padding: 24px 16px;
      }
      .left-sidebar.collapsed { margin-left: -260px; }
      .left-sidebar h3 { font-size: 0.85rem; text-transform: uppercase; color: #6b7280; margin-bottom: 12px; }
      .left-sidebar ul { list-style: none; }
      .left-sidebar li { margin-bottom: 8px; }
      .left-sidebar a { text-decoration: none; color: #4b5563; font-size: 0.95rem; }
      .main-reader { flex: 1; overflow-y: auto; padding: 40px 60px; display: flex; justify-content: center; }
      .manuscript-body { max-width: 650px; width: 100%; line-height: 1.75; font-size: 1.15rem; }
      .right-sidebar { width: 320px; border-left: 1px solid #e5e7eb; background: #ffffff; overflow-y: auto; padding: 24px 16px; }
      .right-sidebar h4 { font-size: 0.9rem; color: #374151; margin-bottom: 16px; }
    `
  }
  return (
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>The Novel Workspace</title>
      <style dangerouslySetInnerHTML={cssStyles} />
    </head>
  )
}

const TopToolbar: FC = () => (
  <header class="toolbar">
    <button id="toggle-toc" onclick="toggleSidebar()">☰ Chapters</button>
    <div class="novel-title">The Novel Workspace</div>
    <button id="auth-status" style="border-color: #ef4444; color: #ef4444;">No Access Token</button>
  </header>
)

const LefNavigation: FC = () => (
  <aside class="left-sidebar" id="left-sidebar">
    <h3>Chapters</h3>
    <ul>
      <li><a href="#" onclick="loadChapter('chapter-1')">Chapter 1: The SOS Event</a></li>
    </ul>
  </aside>
)

const MainReader: FC = () => (
  <main class="main-reader">
    <article class="manuscript-body" id="text-canvas">
      <h1 style="text-align: center; margin-bottom: 24px;">Welcome to The Novel Workspace</h1>
      <p style="color: #6b7280; text-align: center;">Please upload your token or select a chapter to begin viewing model drafts.</p>
    </article>
  </main>
)

const RightFeedbackPanel: FC = () => (
  <aside class="right-sidebar">
    <h4>Comments</h4>
    <div id="comment-stream" style="color: #9ca3af; font-size: 0.9rem;">Click on any line inside the text canvas to view or drop inline notes</div>
  </aside>
)

const ClientScripts: FC = () => {
  const jsCode = {
    __html: `
      function toggleSidebar() {
        const sidebar = document.getElementById('left-sidebar');
        sidebar.classList.toggle('collapsed');
      }
      
      function initializeAuth() {
        const rawLocationSearch = window.location.search;
        const tokenMatch = rawLocationSearch.match(/token=([^&]+)/);

        const urlParams = new URLSearchParams(window.location.search);
        // const token = urlParams.get('token');
        const authStatus = document.getElementById('auth-status');
        if (tokenMatch && tokenMatch[1]) {
          localStorage.setItem('ucan_token', decodeURIComponent(tokenMatch[1]));
          window.history.replaceState({}, document.title, window.location.pathname); // Clean URL
        }
        const storedToken = localStorage.getItem('ucan_token');
        if (storedToken) {
          authStatus.innerText = "✓ Token Active";
          authStatus.style.borderColor = "#10b981";
          authStatus.style.color = "#10b981";
        } else {
          authStatus.innerText = "No Access Token";
          authStatus.style.borderColor = "#ef4444";
          authStatus.style.color = "#ef4444";
        }
      }

      async function loadChapter(slug) {
        const canvas = document.getElementById('text-canvas');
        const token = localStorage.getItem('ucan_token');
        if (!token) {
          alert('Access Denied: No valid token found. Please use your authorized invite link to access the content.');
          return;
        }
        canvas.innerHTML = '<p style="color: #6b7280; text-align: center;">Securely loading chapter...</p>';

        try {
          const response = await fetch('/api/chapter/' + slug, {
            method: 'GET',
            headers: { 'Authorization': 'Bearer ' + token }
          });
          if (!response.ok) {
            if (response.status === 401 || response.status === 403) {
              canvas.innerHTML = '<p style="color: #ef4444; text-align: center;">Unauthorized access. Please check your token or access link.</p>';
            } else if (response.status === 404) {
              canvas.innerHTML = '<p style="color: #ef4444; text-align: center;">Chapter not found. Please ensure the chapter slug is correct.</p>';
            }
            return;
          }
          const chapterText = await response.text();

          canvas.innerHTML = '<h1 style="margin-bottom: 24px;">' + slug.toUpperCase() + '</h1><div style="white-space: pre-wrap;">' + chapterText + '</div>';
        } catch (error) {
          console.error(error);
          canvas.innerHTML = '<h1 style="color: #ef4444; text-align: center;">Network Error</h1>';
        }
      }
        window.onload = initializeAuth;
    `
  }
  return <script dangerouslySetInnerHTML={jsCode} />
}

app.get('/', (c) => {
  // return c.text('Hello Hono!')
  return c.html(
    <html>
      <HeadStyles />
      <body>
        <TopToolbar />
        <div class="workspace-container">
          <LefNavigation />
          <MainReader />
          <RightFeedbackPanel />
        </div>
        <ClientScripts />
      </body>
    </html>
  )
})

export default app
