import { Hono } from 'hono'
import { Delegation } from 'iso-ucan/delegation'
import { FC } from 'hono/jsx' // Import Hono's native JSX engine

import cssContent from './styles.txt?raw' // Import CSS as raw text for inline injection
import jsContent from './scripts.txt?raw' // Import JS as raw text for inline injection

type Bindings = {
  NOVEL_TEXT_KV: KVNamespace
  DB: D1Database
}

const app = new Hono<{ Bindings: Bindings }>()
const AUTHORIZED_ROOT_DID = "did:key:z6Mkm2amevqzfDPo3V9fvV6efLxK4H2DvzuSkrcWFkVisMjJ"

app.get('api/chapter/:slug', async (c) => {
  const slug = c.req.param('slug')
  const authHeader = c.req.header('Authorization')
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return c.text('Unauthorized', 401)
  }
  const token = authHeader.substring(7) // Remove "Bearer " prefix
  try {
    const delegation = await Delegation.fromString(token)
    console.log('Issuer:', delegation.iss, " Root DID:", AUTHORIZED_ROOT_DID)

    if (!delegation.iss || delegation.iss !== AUTHORIZED_ROOT_DID) {
      return c.text('Unauthorized: Token not generated by authorized party', 401)
    }
    console.log('Token expiration:', delegation.exp, 'Current time:', Date.now() / 1000)
    if (delegation.exp && delegation.exp < Date.now() / 1000) {
      console.log('CRITICAL Cloudflare thinks this token is expired. Expiration time:', delegation.exp, 'Current time:', Date.now() / 1000)
      return c.text('Unauthorized: Token has expired', 401)
    }
  } catch (error) {
    console.error('Error verifying token:', error)
    return c.text('Unauthorized: Invalid cryptographic signature', 401)
  }
  const chapterText = await c.env.NOVEL_TEXT_KV.get(slug)
  if (!chapterText) {
    return c.text('Chapter not found', 404)
  }
  return c.text(chapterText)
})

app.post('api/feedback', async (c) => {
  const authHeader = c.req.header('Authorization')
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return c.text('Unauthorized', 401)
  }
  const token = authHeader.substring(7) // Remove "Bearer " prefix
  try {
    const delegation = await Delegation.fromString(token)
    if (!delegation.iss || delegation.iss !== AUTHORIZED_ROOT_DID) {
      return c.text('Unauthorized: Token not generated by authorized party', 401)
    }
    if (delegation.exp && delegation.exp < Date.now() / 1000) {
      return c.text('Unauthorized: Token has expired', 401)
    }

    const feedback = await c.req.json()
    const { chapterSlug, sentenceId, feedbackText } = feedback

    // Store the feedback in the D1 database
    const query = `
    INSERT INTO feedback (chapter_slug, sentence_id, reader_did, feedback)
    VALUES (?, ?, ?, ?)
  `
    await c.env.DB.prepare(query).bind(chapterSlug, sentenceId, delegation.iss, feedbackText).run()

    return c.json({ message: 'Feedback submitted successfully' })
  } catch (error) {
    console.error('Error storing feedback:', error)
    return c.text('Unauthorized: OR Failed to store feedback', 500)
  }
})

const HeadStyles: FC = () => {
  return (
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>The Novel Workspace</title>
      <style dangerouslySetInnerHTML={{ __html: cssContent}} />
    </head>
  )
}

const TopToolbar: FC = () => (
  <header class="toolbar">
    <button id="toggle-toc" onclick="toggleSidebar()">☰ Chapters</button>
    <div class="novel-title">The Novel Workspace</div>
    <button id="auth-status" style="border-color: #ef4444; color: #ef4444;">No Access Token</button>
  </header>
)

const LefNavigation: FC = () => (
  <aside class="left-sidebar" id="left-sidebar">
    <h3>Chapters</h3>
    <ul>
      <li><a href="#" onclick="loadChapter('chapter-1')">Chapter 1: The SOS Event</a></li>
    </ul>
  </aside>
)

const MainReader: FC = () => (
  <main class="main-reader">
    <article class="manuscript-body" id="text-canvas">
      <h1 style="text-align: center; margin-bottom: 24px;">Welcome to The Novel Workspace</h1>
      <p style="color: #6b7280; text-align: center;">Please upload your token or select a chapter to begin viewing model drafts.</p>
    </article>
  </main>
)

const RightFeedbackPanel: FC = () => (
  <aside class="right-sidebar">
    <div id="subsection-nav-container" style="margin-bottom: 24px; padding-bottom:16px; border-bottom: 1px solid #e5e7eb;display:none;">
      <h4 style="font-size: 1rem; text-transform: uppercase; font-weight: 500; color: #6b7280;letter-spacing: 0.05em;margin-bottom: 0.5rem;">On This Page</h4>
      <ul id="subsection-links" style="list-style: none; display: flex; flex-direction: column; gap: 0.5rem; font-size: 0.9rem;"></ul>
    </div>
    <h4>Comments</h4>
    <div id="comment-stream" style="color: #9ca3af; font-size: 0.9rem;">Click on any line inside the text canvas to view or drop inline notes</div>
  </aside>
)

const ClientScripts: FC = () => {
  return <script dangerouslySetInnerHTML={{__html: jsContent}} />
}

app.get('/', (c) => {
  // return c.text('Hello Hono!')
  return c.html(
    <html>
      <HeadStyles />
      <body>
        <TopToolbar />
        <div class="workspace-container">
          <LefNavigation />
          <MainReader />
          <RightFeedbackPanel />
        </div>
        <ClientScripts />
      </body>
    </html>
  )
})

export default app
