import { Hono } from 'hono'
import { Delegation } from 'iso-ucan/delegation'

type Bindings = {
  NOVEL_TEXT_KV: KVNamespace
  DB: D1Database
}

const app = new Hono<{ Bindings: Bindings }>()
const AUTHORIZED_ROOT_DID = "did:key:z6Mkm2amevqzfDPo3V9fvV6efLxK4H2DvzuSkrcWFkVisMjJ"

app.get('api/chapter/:slug', async (c) => {
  const slug = c.req.param('slug')
  const authHeader = c.req.header('Authorization')
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return c.text('Unauthorized', 401)
  }
  const token = authHeader.substring(7) // Remove "Bearer " prefix
  try {
    const delegation = await Delegation.fromString(token)
    if (!delegation.iss || delegation.iss !== AUTHORIZED_ROOT_DID) {
      return c.text('Unauthorized: Token not generated by authorized party', 401)
    }
    if (delegation.exp && delegation.exp < Date.now() / 1000) {
      return c.text('Unauthorized: Token has expired', 401)
    }
  } catch (error) {
    return c.text('Unauthorized: Invalid cryptographic signature', 401)
  }
  const chapterText = await c.env.NOVEL_TEXT_KV.get(slug)
  if (!chapterText) {
    return c.text('Chapter not found', 404)
  }
  return c.text(chapterText)
})

app.post('api/feedback', async (c) => {
  const feedback = await c.req.json()
  const { chapterSlug, feedbackText } = feedback

  // Store the feedback in the D1 database
  const query = `
    INSERT INTO feedback (chapter_slug, feedback_text)
    VALUES (?, ?)
  `
  await c.env.DB.prepare(query).bind(chapterSlug, feedbackText).run()

  return c.json({ message: 'Feedback submitted successfully' })
})

app.get('/', (c) => {
  return c.text('Hello Hono!')
})

export default app
